// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvxgcxqutakvulcombjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2eGdjeHF1dGFrdnVsY29tYmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTM5NTUsImV4cCI6MjA2MTMyOTk1NX0.YkwLEroUB6ICxZNqIXkOfJiNb4yDgsoE1bjGjEZPj9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);